
root: true

env:
  es6: true
  node: true

extends: standard

parserOptions:
  ecmaVersion: 2018

rules:
  comma-dangle:
    - error
    - always-multiline

  operator-linebreak:
    - error
    - after
    - overrides:
        '&&': before
        '||': before

  semi:
    - error
    - always
